# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: 'Default'

stages:
 - stage: build
   jobs:
     - job: run_on_linux

       steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              npm audit fix
              npm install
            displayName: 'npm install'
              

            
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: tar
              archiveFile: $(Build.ArtifactStagingDirectory)/bootcamp-app/webApp.tar
              replaceExistingArchive: true
              
             
          # - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar
          #   artifact: drop
          
          - task: PublishBuildArtifacts@1
            inputs:
             pathtoPublish: '$(Build.ArtifactStagingDirectory)/bootcamp-app/webApp.tar' 
             artifactName: 'app-artifact'
            displayName: 'Publish Artifact'


              

          # - task: UniversalPackages@0
          #   inputs:
          #     command: 'publish'
          #     publishDirectory: '$(Build.ArtifactStagingDirectory)/bootcamp-app'
          #     feedsToUsePublish: 'internal'
          #     vstsFeedPublish: 'e8d720f9-0860-4ddd-88fb-23050ed2bbf4'
          #     vstsFeedPackagePublish: 'webApp-artifact'
          #     versionOption: 'patch'
          #     packagePublishDescription: 'publish the zip into azure artifact'
              
            

           

 - stage: Deploy
   jobs:
     - job: run_deploy

       steps:

        - task: Ansible@0
          inputs:
            ansibleInterface: 'agentMachine'
            playbookPathOnAgentMachine: '/home/adminuser/ansible-bootcamp/playbook.yaml'
            inventoriesAgentMachine: 'file'
            inventoryFileOnAgentMachine: '/home/adminuser/ansible-bootcamp/inventory'